version: '3.5'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER= $MYSQLDB_USER
    ports:
      - ${MYSQLDB_LOCAL_PORT}:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    env_file: ./.env
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8000:8080

  discovery:
    container_name: discovery
    image: consul:1.6.3
    ports:
      - 8500:8500

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"


  service_catalogue:
    container_name: servicecatalogue
    image: service-catalogue
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=  -DRABBITMQ_HOST=rabbitmq -DCONSUL_HOST=discovery -DCONSUL_PORT=8500 
          -DDB_HOST=mysqldb -DDB_PORT=3306 -DKEY_HOST=keycloak
    depends_on:
      - mysqldb
      - discovery
      - keycloak
      - rabbitmq
volumes:
  db:
