server:
  port: 0
spring:
  application:
    name: @project.artifactId@
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/catalogue?useSSL=false
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEY_HOST:localhost}:8080/auth/realms/clickCollect/protocol/openid-connect/certs

  main:
    allow-bean-definition-overriding: true
