server:
  port: 8080
spring:
  application:
    name: @project.artifactId@
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/catalogue
    username: root
    password: root
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  main:
    allow-bean-definition-overriding: true

queue:
  sender:
    name:
      listItemQueue
  listener:
    name:
      itemQueue