server:
  port: 8080
spring:
  application:
    name: @project.artifactId@
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/catalogue?useSSL=false
    username: root
    password: root
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest

  main:
    allow-bean-definition-overriding: true

queue:
  sender:
    name:
      listItemQueue
  listener:
    name:
      itemQueue

