FROM maven:3.8.2-jdk-11
COPY target/servicecatalogue-0.0.1-SNAPSHOT.jar servicecatalogue-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/servicecatalogue-0.0.1-SNAPSHOT.jar"]
#RUN mvn clean install
#CMD mvn spring-boot:run
